# -*- mode: ruby -*-
# vi: set ft=ruby :

$install = <<-SCRIPT
sudo yum update -y

# Install Docker and Ansible.
sudo yum install -y docker ansible
sudo service docker start
sudo usermod -a -G docker vagrant

# Install docker-compose.
sudo curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "gbailey/amzn2"

  config.vm.network "forwarded_port", guest: 8080, host: 8080

  config.vm.synced_folder "../../outline", "/project"

  config.vm.provision "shell", inline: $install
  config.vm.provision "ansible_local" do |ansible|
    ansible.install = false
    ansible.playbook = "provisioning/playbook.yml"
    ansible.galaxy_role_file = "provisioning/requirements.yml"
    ansible.galaxy_roles_path = "/home/vagrant/.ansible/roles/"
    ansible.galaxy_command = "ansible-galaxy install --role-file=%{role_file} --roles-path=%{roles_path}"
  end
end
